# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1136, 534)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(9, 39, 1120, 380))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.frame)
        self.mdiArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mdiArea.setStyleSheet("")
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.wd_cadastro = QtWidgets.QWidget()
        self.wd_cadastro.setMinimumSize(QtCore.QSize(1024, 380))
        self.wd_cadastro.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wd_cadastro.setObjectName("wd_cadastro")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wd_cadastro)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.wd_cadastro)
        self.frame_2.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(1032, 600))
        self.scrollArea.setMaximumSize(QtCore.QSize(1024, 600))
        self.scrollArea.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1018, 1418))
        self.scrollAreaWidgetContents_4.setStyleSheet("")
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_17.setEnabled(True)
        self.frame_17.setMinimumSize(QtCore.QSize(1000, 1400))
        self.frame_17.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frame_17.setMouseTracking(False)
        self.frame_17.setTabletTracking(False)
        self.frame_17.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame_17.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame_17.setAcceptDrops(False)
        self.frame_17.setWhatsThis("")
        self.frame_17.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_2 = QtWidgets.QLabel(self.frame_17)
        self.label_2.setGeometry(QtCore.QRect(241, 390, 481, 111))
        self.label_2.setStyleSheet("image: url(:/Imagens/Peixe.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_17)
        self.frame_6.setGeometry(QtCore.QRect(70, 300, 861, 8))
        self.frame_6.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_17)
        self.frame_9.setGeometry(QtCore.QRect(77, 876, 861, 8))
        self.frame_9.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.btn_alterarInv_2 = QtWidgets.QPushButton(self.frame_17)
        self.btn_alterarInv_2.setEnabled(False)
        self.btn_alterarInv_2.setGeometry(QtCore.QRect(100, 1300, 100, 40))
        self.btn_alterarInv_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_alterarInv_2.setFont(font)
        self.btn_alterarInv_2.setStyleSheet("QPushButton#btn_alterarInv{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(100, 19,11, 219), stop:1 rgba(0, 0, 0, 80));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_alterarInv:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_alterarInv:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagens/registro (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_alterarInv_2.setIcon(icon)
        self.btn_alterarInv_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_alterarInv_2.setObjectName("btn_alterarInv_2")
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_17)
        self.layoutWidget_5.setGeometry(QtCore.QRect(740, 1290, 208, 42))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.btn_conclusao_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_conclusao_2.setEnabled(False)
        self.btn_conclusao_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_conclusao_2.setFont(font)
        self.btn_conclusao_2.setStyleSheet("QPushButton#btn_conclusao{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(100, 19,11, 219), stop:1 rgba(0, 0, 0, 80));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_conclusao:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_conclusao:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Imagens/salve-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_conclusao_2.setIcon(icon1)
        self.btn_conclusao_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_conclusao_2.setObjectName("btn_conclusao_2")
        self.horizontalLayout_35.addWidget(self.btn_conclusao_2)
        self.btn_cancela_investiga_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_cancela_investiga_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_cancela_investiga_2.setFont(font)
        self.btn_cancela_investiga_2.setStyleSheet("QPushButton#btn_cancela_investiga{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(100, 19,11, 219), stop:1 rgba(0, 0, 0, 80));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_cancela_investiga:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_cancela_investiga:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Imagens/cancelar (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancela_investiga_2.setIcon(icon2)
        self.btn_cancela_investiga_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_cancela_investiga_2.setObjectName("btn_cancela_investiga_2")
        self.horizontalLayout_35.addWidget(self.btn_cancela_investiga_2)
        self.layoutWidget_8 = QtWidgets.QWidget(self.frame_17)
        self.layoutWidget_8.setGeometry(QtCore.QRect(60, 370, 114, 126))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_35.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_10.addWidget(self.label_35)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_iniciar_investigacao_2 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.btn_iniciar_investigacao_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_iniciar_investigacao_2.setFont(font)
        self.btn_iniciar_investigacao_2.setStyleSheet("QPushButton#btn_iniciar_investigacao{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(100, 19,11, 219), stop:1 rgba(0, 0, 0, 80));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_iniciar_investigacao:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_iniciar_investigacao:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Imagens/investigacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_iniciar_investigacao_2.setIcon(icon3)
        self.btn_iniciar_investigacao_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_iniciar_investigacao_2.setObjectName("btn_iniciar_investigacao_2")
        self.verticalLayout_13.addWidget(self.btn_iniciar_investigacao_2)
        self.label_111 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(9)
        font.setBold(True)
        self.label_111.setFont(font)
        self.label_111.setStyleSheet("color: rgb(0,0,0);")
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_13.addWidget(self.label_111)
        self.txt_paciente_4 = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.txt_paciente_4.setEnabled(False)
        self.txt_paciente_4.setMinimumSize(QtCore.QSize(100, 21))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.txt_paciente_4.setFont(font)
        self.txt_paciente_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_paciente_4.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_paciente_4.setObjectName("txt_paciente_4")
        self.verticalLayout_13.addWidget(self.txt_paciente_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_13)
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_17)
        self.layoutWidget_6.setGeometry(QtCore.QRect(52, 532, 905, 755))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_100 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_100.setFont(font)
        self.label_100.setStyleSheet("color: rgb(0,0,0);")
        self.label_100.setObjectName("label_100")
        self.horizontalLayout_23.addWidget(self.label_100)
        self.txt_pessoas_9 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_9.setEnabled(False)
        self.txt_pessoas_9.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_9.setObjectName("txt_pessoas_9")
        self.horizontalLayout_23.addWidget(self.txt_pessoas_9)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_101 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_101.setFont(font)
        self.label_101.setStyleSheet("color: rgb(0,0,0);")
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_41.addWidget(self.label_101)
        self.txt_pessoas_10 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_10.setEnabled(False)
        self.txt_pessoas_10.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_10.setObjectName("txt_pessoas_10")
        self.horizontalLayout_41.addWidget(self.txt_pessoas_10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_102 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_102.setFont(font)
        self.label_102.setStyleSheet("color: rgb(0,0,0);")
        self.label_102.setObjectName("label_102")
        self.horizontalLayout_42.addWidget(self.label_102)
        self.txt_processos_2 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_processos_2.setEnabled(False)
        self.txt_processos_2.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_processos_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_processos_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_processos_2.setObjectName("txt_processos_2")
        self.horizontalLayout_42.addWidget(self.txt_processos_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_103 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_103.setFont(font)
        self.label_103.setStyleSheet("color: rgb(0,0,0);")
        self.label_103.setObjectName("label_103")
        self.horizontalLayout_43.addWidget(self.label_103)
        self.txt_pessoas_11 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_11.setEnabled(False)
        self.txt_pessoas_11.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_11.setObjectName("txt_pessoas_11")
        self.horizontalLayout_43.addWidget(self.txt_pessoas_11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_104 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_104.setFont(font)
        self.label_104.setStyleSheet("color: rgb(0,0,0);")
        self.label_104.setObjectName("label_104")
        self.horizontalLayout_44.addWidget(self.label_104)
        self.txt_equipamentos_2 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_equipamentos_2.setEnabled(False)
        self.txt_equipamentos_2.setMinimumSize(QtCore.QSize(800, 0))
        self.txt_equipamentos_2.setMaximumSize(QtCore.QSize(380, 16777215))
        self.txt_equipamentos_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_equipamentos_2.setObjectName("txt_equipamentos_2")
        self.horizontalLayout_44.addWidget(self.txt_equipamentos_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_105 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_105.setFont(font)
        self.label_105.setStyleSheet("color: rgb(0,0,0);")
        self.label_105.setObjectName("label_105")
        self.horizontalLayout_45.addWidget(self.label_105)
        self.txt_ambiente_2 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_ambiente_2.setEnabled(False)
        self.txt_ambiente_2.setMinimumSize(QtCore.QSize(755, 0))
        self.txt_ambiente_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.txt_ambiente_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_ambiente_2.setObjectName("txt_ambiente_2")
        self.horizontalLayout_45.addWidget(self.txt_ambiente_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_45)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_15.addWidget(self.label_39)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_93 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("color: rgb(0,0,0);")
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_46.addWidget(self.label_93)
        self.txt_pessoas_12 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_12.setEnabled(False)
        self.txt_pessoas_12.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_12.setObjectName("txt_pessoas_12")
        self.horizontalLayout_46.addWidget(self.txt_pessoas_12)
        self.verticalLayout_18.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_106 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_106.setFont(font)
        self.label_106.setStyleSheet("color: rgb(0,0,0);")
        self.label_106.setObjectName("label_106")
        self.horizontalLayout_47.addWidget(self.label_106)
        self.txt_pessoas_13 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_13.setEnabled(False)
        self.txt_pessoas_13.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_13.setObjectName("txt_pessoas_13")
        self.horizontalLayout_47.addWidget(self.txt_pessoas_13)
        self.verticalLayout_18.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_107 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_107.setFont(font)
        self.label_107.setStyleSheet("color: rgb(0,0,0);")
        self.label_107.setObjectName("label_107")
        self.horizontalLayout_48.addWidget(self.label_107)
        self.txt_pessoas_14 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_14.setEnabled(False)
        self.txt_pessoas_14.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_14.setObjectName("txt_pessoas_14")
        self.horizontalLayout_48.addWidget(self.txt_pessoas_14)
        self.verticalLayout_18.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_108 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_108.setFont(font)
        self.label_108.setStyleSheet("color: rgb(0,0,0);")
        self.label_108.setObjectName("label_108")
        self.horizontalLayout_49.addWidget(self.label_108)
        self.txt_pessoas_15 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_15.setEnabled(False)
        self.txt_pessoas_15.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_15.setObjectName("txt_pessoas_15")
        self.horizontalLayout_49.addWidget(self.txt_pessoas_15)
        self.verticalLayout_18.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_109 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(10)
        font.setBold(False)
        self.label_109.setFont(font)
        self.label_109.setStyleSheet("color: rgb(0,0,0);")
        self.label_109.setObjectName("label_109")
        self.horizontalLayout_17.addWidget(self.label_109)
        self.txt_pessoas_16 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.txt_pessoas_16.setEnabled(False)
        self.txt_pessoas_16.setMinimumSize(QtCore.QSize(811, 0))
        self.txt_pessoas_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_pessoas_16.setObjectName("txt_pessoas_16")
        self.horizontalLayout_17.addWidget(self.txt_pessoas_16)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.verticalLayout_15.addLayout(self.verticalLayout_18)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_19.addWidget(self.label_40)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(11)
        font.setBold(True)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("color: rgb(0,0,0);")
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_19.addWidget(self.label_87)
        self.txt_recomendacao_3 = QtWidgets.QTextEdit(self.layoutWidget_6)
        self.txt_recomendacao_3.setEnabled(True)
        self.txt_recomendacao_3.setMinimumSize(QtCore.QSize(811, 51))
        self.txt_recomendacao_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 50px;\n"
"border-bottom-right-radius: 10px;")
        self.txt_recomendacao_3.setObjectName("txt_recomendacao_3")
        self.verticalLayout_19.addWidget(self.txt_recomendacao_3)
        self.verticalLayout_14.addLayout(self.verticalLayout_19)
        self.layoutWidget_9 = QtWidgets.QWidget(self.frame_17)
        self.layoutWidget_9.setGeometry(QtCore.QRect(842, 360, 112, 149))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.btn_buscarInv_2 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.btn_buscarInv_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_buscarInv_2.setFont(font)
        self.btn_buscarInv_2.setStyleSheet("QPushButton#btn_buscarInv{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(100, 19,11, 219), stop:1 rgba(0, 0, 0, 80));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_buscarInv:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_buscarInv:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Imagens/historia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscarInv_2.setIcon(icon4)
        self.btn_buscarInv_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_buscarInv_2.setObjectName("btn_buscarInv_2")
        self.verticalLayout_20.addWidget(self.btn_buscarInv_2)
        self.label_115 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(9)
        font.setBold(True)
        self.label_115.setFont(font)
        self.label_115.setStyleSheet("color: rgb(0,0,0);")
        self.label_115.setAlignment(QtCore.Qt.AlignCenter)
        self.label_115.setObjectName("label_115")
        self.verticalLayout_20.addWidget(self.label_115)
        self.txt_tratativa_2 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.txt_tratativa_2.setEnabled(True)
        self.txt_tratativa_2.setMinimumSize(QtCore.QSize(100, 21))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.txt_tratativa_2.setFont(font)
        self.txt_tratativa_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.txt_tratativa_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_tratativa_2.setObjectName("txt_tratativa_2")
        self.verticalLayout_20.addWidget(self.txt_tratativa_2)
        self.btn_editarInv_2 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.btn_editarInv_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_editarInv_2.setFont(font)
        self.btn_editarInv_2.setStyleSheet("QPushButton#btn_editarInv{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(100, 19,11, 219), stop:1 rgba(0, 0, 0, 80));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_btn_editarInv:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_editarInv:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_editarInv_2.setIcon(icon)
        self.btn_editarInv_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_editarInv_2.setObjectName("btn_editarInv_2")
        self.verticalLayout_20.addWidget(self.btn_editarInv_2)
        self.label_41 = QtWidgets.QLabel(self.frame_17)
        self.label_41.setGeometry(QtCore.QRect(60, 310, 860, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.layoutWidget_10 = QtWidgets.QWidget(self.frame_17)
        self.layoutWidget_10.setGeometry(QtCore.QRect(66, 21, 866, 266))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_23.addWidget(self.label_42)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_20.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_50.addWidget(self.label_20)
        self.cb_setor_2 = QtWidgets.QComboBox(self.layoutWidget_10)
        self.cb_setor_2.setEnabled(False)
        self.cb_setor_2.setMinimumSize(QtCore.QSize(250, 23))
        self.cb_setor_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cb_setor_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.cb_setor_2.setObjectName("cb_setor_2")
        self.cb_setor_2.addItem("")
        self.cb_setor_2.setItemText(0, "")
        self.horizontalLayout_50.addWidget(self.cb_setor_2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_6.addWidget(self.label_43)
        self.cd_tipo_rnc_3 = QtWidgets.QComboBox(self.layoutWidget_10)
        self.cd_tipo_rnc_3.setEnabled(False)
        self.cd_tipo_rnc_3.setMinimumSize(QtCore.QSize(751, 23))
        self.cd_tipo_rnc_3.setMaximumSize(QtCore.QSize(751, 16777215))
        self.cd_tipo_rnc_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.cd_tipo_rnc_3.setObjectName("cd_tipo_rnc_3")
        self.cd_tipo_rnc_3.addItem("")
        self.cd_tipo_rnc_3.setItemText(0, "")
        self.horizontalLayout_6.addWidget(self.cd_tipo_rnc_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_6)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("\n"
"color:rgba(255, 255, 255, 210);")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_27.addWidget(self.label_44)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_45.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_51.addWidget(self.label_45)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_10)
        self.comboBox_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_51.addWidget(self.comboBox_2)
        self.verticalLayout_27.addLayout(self.horizontalLayout_51)
        self.verticalLayout_26.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_54.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_54.addWidget(self.label_47)
        self.horizontalLayout_53.addLayout(self.horizontalLayout_54)
        self.cb_funcao_4 = QtWidgets.QComboBox(self.layoutWidget_10)
        self.cb_funcao_4.setEnabled(True)
        self.cb_funcao_4.setMinimumSize(QtCore.QSize(240, 23))
        self.cb_funcao_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.cb_funcao_4.setObjectName("cb_funcao_4")
        self.cb_funcao_4.addItem("")
        self.cb_funcao_4.setItemText(0, "")
        self.cb_funcao_4.addItem("")
        self.cb_funcao_4.addItem("")
        self.cb_funcao_4.addItem("")
        self.horizontalLayout_53.addWidget(self.cb_funcao_4)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_56.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_56.addWidget(self.label_49)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_56)
        self.dt_rnc_3 = QtWidgets.QDateEdit(self.layoutWidget_10)
        self.dt_rnc_3.setEnabled(False)
        self.dt_rnc_3.setMinimumSize(QtCore.QSize(150, 23))
        self.dt_rnc_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.dt_rnc_3.setAlignment(QtCore.Qt.AlignCenter)
        self.dt_rnc_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 2), QtCore.QTime(15, 0, 0)))
        self.dt_rnc_3.setCalendarPopup(True)
        self.dt_rnc_3.setObjectName("dt_rnc_3")
        self.horizontalLayout_55.addWidget(self.dt_rnc_3)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_55)
        self.verticalLayout_28.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_58.addWidget(self.label_24)
        self.horizontalLayout_57.addLayout(self.horizontalLayout_58)
        self.cb_funcao_outros_3 = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.cb_funcao_outros_3.setEnabled(False)
        self.cb_funcao_outros_3.setMinimumSize(QtCore.QSize(220, 23))
        self.cb_funcao_outros_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 2px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius : 3px;")
        self.cb_funcao_outros_3.setObjectName("cb_funcao_outros_3")
        self.horizontalLayout_57.addWidget(self.cb_funcao_outros_3)
        self.verticalLayout_28.addLayout(self.horizontalLayout_57)
        self.verticalLayout_26.addLayout(self.verticalLayout_28)
        self.verticalLayout_25.addLayout(self.verticalLayout_26)
        self.verticalLayout_12.addWidget(self.frame_17)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(9, 9, 75, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.wd_cadastro.setWindowTitle(_translate("Form", "Subwindow"))
        self.btn_alterarInv_2.setText(_translate("Form", "ALTERAR"))
        self.btn_conclusao_2.setText(_translate("Form", "CONCLUIR"))
        self.btn_cancela_investiga_2.setText(_translate("Form", "CANCELAR"))
        self.label_35.setText(_translate("Form", "Iniciar Tratativa"))
        self.btn_iniciar_investigacao_2.setText(_translate("Form", "TRATATIVA"))
        self.label_111.setText(_translate("Form", "NC:"))
        self.label_100.setText(_translate("Form", "Método"))
        self.txt_pessoas_9.setToolTip(_translate("Form", "como a forma de desenvolver o trabalho influencia o problema?"))
        self.label_101.setText(_translate("Form", "Mão de Obra:"))
        self.txt_pessoas_10.setToolTip(_translate("Form", "como as pessoas envolvidas na atividade influenciam o problema?"))
        self.label_102.setText(_translate("Form", "Máquina:"))
        self.txt_processos_2.setToolTip(_translate("Form", "como os equipamentos utilizados no processo influenciam o problema?"))
        self.label_103.setText(_translate("Form", "Medida:"))
        self.txt_pessoas_11.setToolTip(_translate("Form", "como as métricas utilizadas para medir o desenvolvimento da atividade influenciam o problema?"))
        self.label_104.setText(_translate("Form", "Material:"))
        self.txt_equipamentos_2.setToolTip(_translate("Form", "como a qualidade e o tipo dos materiais utilizados influenciam o problema?"))
        self.label_105.setText(_translate("Form", "Meio Ambiente:"))
        self.txt_ambiente_2.setToolTip(_translate("Form", "como o meio em que a atividade está sendo desenvolvida influencia o problema?"))
        self.label_39.setText(_translate("Form", "PLANO DE AÇÃO"))
        self.label_93.setText(_translate("Form", "O Que?"))
        self.label_106.setText(_translate("Form", "Por que?"))
        self.label_107.setText(_translate("Form", "Quem?"))
        self.label_108.setText(_translate("Form", "Quando?"))
        self.label_109.setText(_translate("Form", "Como?"))
        self.label_40.setText(_translate("Form", "SETOR DE QUALIDADE"))
        self.label_87.setText(_translate("Form", "Análise de eficácia"))
        self.txt_recomendacao_3.setToolTip(_translate("Form", "Análise de Eficácia será preenchida pelo setor de Qualidade"))
        self.btn_buscarInv_2.setText(_translate("Form", "BUSCAR"))
        self.label_115.setText(_translate("Form", "NC:"))
        self.btn_editarInv_2.setText(_translate("Form", "EDITAR"))
        self.label_41.setText(_translate("Form", "LÍDER IMEDIATO"))
        self.label_42.setText(_translate("Form", "INFORMAÇÕES DA NÃO CONFORMIDADE"))
        self.label_20.setText(_translate("Form", "Setor de ocorrência da Não Conformidade:"))
        self.label_43.setText(_translate("Form", "Não Conformidade:"))
        self.label_44.setText(_translate("Form", "SETOR DE QUALIDADE"))
        self.label_45.setText(_translate("Form", "Status NC"))
        self.comboBox_2.setItemText(0, _translate("Form", "Aberta"))
        self.comboBox_2.setItemText(1, _translate("Form", "Em Andamento"))
        self.comboBox_2.setItemText(2, _translate("Form", "Com Pendências"))
        self.comboBox_2.setItemText(3, _translate("Form", "Concluído"))
        self.comboBox_2.setItemText(4, _translate("Form", "Não Procedente"))
        self.label_46.setText(_translate("Form", "Classificação"))
        self.label_47.setText(_translate("Form", "*"))
        self.cb_funcao_4.setToolTip(_translate("Form", "Não Conformidade Maior: Quando um requisito inteiro da norma não é atendido, caracterizando uma falha sistêmica. Também poderão ser emitidas quando falhas existirem nos produtos e for constatado que os mesmos cheguem ao cliente. Caracteriza também o acúmulo de não conformidades menores a um mesmo item normativo ou então a reincidência de uma não conformidade menor identificada em uma auditoria externa anterior;\n"
"\n"
"Não Conformidade Menor: Lapso do controle de um requisito pré-estabelecido. Apesar de não ser grave, indica não cumprimento de um processo específico;\n"
"\n"
"Oportunidade de Melhoria: Melhoria significativa diagnosticada que possa evoluir algum processo e diminuir ou eliminar as não conformidades."))
        self.cb_funcao_4.setItemText(1, _translate("Form", "Oportunidade de Melhoria"))
        self.cb_funcao_4.setItemText(2, _translate("Form", "Maior"))
        self.cb_funcao_4.setItemText(3, _translate("Form", "Menor"))
        self.label_48.setText(_translate("Form", "Prazo para Análise de Eficácia"))
        self.label_49.setText(_translate("Form", "*"))
        self.label_24.setText(_translate("Form", "Abrangência"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton.clicked.connect(self.abriwdCadastro)


    def abriwdCadastro(self):
        self.wd_cadastro.show()
        self.wd_cadastro.showMaximized()
